export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

// PRODUCTS
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";

export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

// CART
export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const LOAD_CART = "LOAD_CART";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const SET_PAYMENT_METHOD = "SET_PAYMENT_METHOD";

// ORDER
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

// ADMIN
export const ADMIN_GET_ALL_USERS_SUCCESS = "ADMIN_GET_ALL_USERS_SUCCESS";
export const ADMIN_GET_ALL_USERS_FAIL = "ADMIN_GET_ALL_USERS_FAIL";

export const ADMIN_GET_USER_BY_ID_SUCCESS = "ADMIN_GET_USER_BY_ID_SUCCESS";
export const ADMIN_GET_USER_BY_ID_FAIL = "ADMIN_GET_USER_BY_ID_FAIL";

export const ADMIN_USER_UPDATE_SUCCESS = "ADMIN_USER_UPDATE_SUCCESS";
export const ADMIN_USER_UPDATE_FAIL = "ADMIN_USER_UPDATE_FAIL";

export const ADMIN_GET_ALL_PRODUCT_SUCCESS = "ADMIN_GET_ALL_PRODUCT_SUCCESS";
export const ADMIN_GET_ALL_PRODUCT_FAIL = "ADMIN_GET_ALL_PRODUCT_FAIL";

export const ADMIN_PRODUCT_UPDATE_SUCCESS = "ADMIN_PRODUCT_UPDATE_SUCCESS";
export const ADMIN_PRODUCT_UPDATE_FAIL = "ADMIN_PRODUCT_UPDATE_FAIL";

export const ADMIN_PRODUCT_CREATE_SUCCESS = "ADMIN_PRODUCT_CREATE_SUCCESS";
export const ADMIN_PRODUCT_CREATE_FAIL = "ADMIN_PRODUCT_CREATE_FAIL";

export const ADMIN_GET_PRODUCT_BY_ID_SUCCESS =
  "ADMIN_GET_PRODUCT_BY_ID_SUCCESS";
export const ADMIN_GET_PRODUCT_BY_ID_FAIL = "ADMIN_GET_PRODUCT_BY_ID_FAIL";

export const ADMIN_GET_ALL_ORDERS_SUCCESS = "ADMIN_GET_ALL_ORDERS_SUCCESS";
export const ADMIN_GET_ALL_ORDERS_FAIL = "ADMIN_GET_ALL_ORDERS_FAIL";

export const ADMIN_GET_ORDER_BY_ID_SUCCESS = "ADMIN_GET_ORDER_BY_ID_SUCCESS";
export const ADMIN_GET_ORDER_BY_ID_FAIL = "ADMIN_GET_ORDER_BY_ID_FAIL";
